GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/643ee9f7b9cbbfc9a3f592ba

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Human",
    "subscriberToChannel": "Isaac Tonyloi"
}

###
DELETE  http://localhost:3000/subscribers/643ee9f7b9cbbfc9a3f592ba

###

PATCH http://localhost:3000/subscribers/643ee9f7b9cbbfc9a3f592ba
Content-Type: application/json


{
    "name": "Amazing SofwareDevloper"
}